### ISSUE TITLE
Can you tell me how to use this?

### ISSUE THREAD

**Issue by SamDecrock** [northshorenetworks/proxy-dns#5]
I installed the latest Node.js (v6) on OS X and I'm getting the following error:

```
import ProxyDNS from 'proxy-dns';
^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

I'm sure it's related to ES6, but I don't know how to solve it.

Thanks,
Sam

**Comment by dcharbonnier** [comment]
`const ProxyDNS = require('proxy-dns').default;`

**Comment by SamDecrock** [comment]
Thanks, I was new to ES6 at that time ;-)
